POST http://localhost:3000/signin
Content-Type: application/json

{
    "email":"a@b.com",
    "password":"password"
}

###

POST http://localhost:3000/signup
Content-Type: application/json

{
    "email":"a@b.com",
    "password":"password"
//    "name":"name",
//    "about":"about"
}

###

GET http://localhost:3000/users/m
Content-Type: application/json
Authorization: {{user1_token}}

###

GET http://localhost:3000/users/636928ce9c3efa000f73d523
Content-Type: application/json
Authorization: {{user1_token}}

###
