POST http://localhost:3000/signin
Content-Type: application/json

{
    "email":"a@b.com",
    "password":"password"
}

###

POST http://localhost:3000/signup
Content-Type: application/json

{
    "email":"a@b.com",
    "password":"password"
//    "name":"name",
//    "about":"about"
}

###

GET http://localhost:3000/users/me
Content-Type: application/json
Authorization: {{user1_token}}

###

GET http://localhost:3000/users/{{user2_id}}
Content-Type: application/json
Authorization: {{user1_token}}

###
